# Generated by Django 5.1.5 on 2025-01-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_features", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
