# Generated by Django 5.2 on 2025-04-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_features', '0006_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='in_showcase',
            field=models.BooleanField(default=False),
        ),
    ]
