# Generated by Django 5.1.5 on 2025-04-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map_features", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date_time",
        ),
    ]
