# Generated by Django 5.1.5 on 2025-04-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_features", "0002_remove_event_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_marketing_user",
            field=models.BooleanField(default=False),
        ),
    ]
